name: Release Build

on:
  release:
    types: [published]  # Only runs when a new release is published

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8
      - name: Cargo version
        run: cargo --version
      - name: Run tests
        run: cargo test --all-features --locked
      - name: Build release binary
        shell: bash
        run: ./scripts/build_release.sh

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp target/release/tool-tool artifacts/

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release-windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.90.0
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8
      - name: Cargo version
        run: cargo --version
      - name: Run tests
        run: cargo test --all-features --locked
      - name: Build release binary
        shell: bash
        run: ./scripts/build_release.sh

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp target/release/tool-tool.exe artifacts/

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}